In [1]:
#comeco tratamento e nomeacoes
import pandas as pd
import numpy as np
tabela = pd.read_csv('Sample - Superstore.csv', sep=',', encoding='latin1')
display(tabela)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [2]:
#tratando e analisando

# qtd linhas e colunas
display(tabela.shape)
display(tabela.columns)

#alterando datas para tipo date
tabela['Order Date'] = pd.to_datetime(tabela['Order Date'])
tabela['Ship Date'] = pd.to_datetime(tabela['Ship Date'])

display(tabela.info())

#verificando duplicatas
tabela.duplicated().sum()

#tabela.describe(include= 'object')
tabela.describe()

(9994, 21)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 1.6 MB

None

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [3]:
#analises
#lucro total
lucro = tabela['Profit'].sum()
print(lucro)

#faturamento
faturamento = tabela['Sales'].sum()
print(faturamento)

#Quais categorias mais vendem?
cat_popular = tabela[['Category', 'Quantity']].groupby('Category').sum()
cat_popular = cat_popular.sort_values(by = 'Quantity', ascending = False)
display(cat_popular)

#Quais categorias mais lucram?
cat_lucro = tabela[['Category', 'Profit']].groupby('Category').sum()
cat_lucro = cat_lucro.sort_values(by = 'Profit', ascending = False)
cat_lucro["Profit"] = cat_lucro["Profit"].map("R${:,.2f}".format)
display(cat_lucro)

#Quais estados mais faturam?
estado_lucro = tabela[['State', 'Profit']].groupby('State').sum()
estado_lucro = estado_lucro.sort_values(by = 'Profit', ascending= False)
estado_lucro['Profit'] = estado_lucro['Profit'].map("R${:,.2f}".format)
#display(estado_lucro)

#O desconto impacta negativamente o lucro?

descontos = tabela[['Discount', 'Profit']].groupby('Discount').sum()
descontos = descontos.sort_values(by = 'Profit', ascending = False)
descontos['Profit'] = descontos['Profit'].map("R${:,.2f}".format)
display(descontos)

#Como as vendas evoluíram entre 2014 e 2017?

analise_por_ano = tabela[['Order Date', 'Profit']].groupby('Order Date').sum()
analise_por_ano = analise_por_ano.sort_values(by = 'Order Date', ascending = True)
analise_por_ano['Profit'] = analise_por_ano['Profit'].map("R${:,.2f}".format)
display(analise_por_ano)

286397.0217
2297200.8603

                 Quantity
Category
Office Supplies     22906
Furniture            8028
Technology           6939

                       Profit
Category
Technology       R$145,454.95
Office Supplies  R$122,490.80
Furniture         R$18,451.27

                Profit
Discount
0.00      R$320,987.60
0.20       R$90,337.31
0.10        R$9,029.18
0.15        R$1,418.99
0.32       R$-2,391.14
0.45       R$-2,493.11
0.60       R$-5,944.66
0.30      R$-10,369.28
0.50      R$-20,506.43
0.40      R$-23,057.05
0.80      R$-30,539.04
0.70      R$-40,075.36

                Profit
Order Date
2014-01-03      R$5.55
2014-01-04    R$-65.99
2014-01-05      R$4.88
2014-01-06  R$1,358.05
2014-01-07    R$-71.96
...                ...
2017-12-26     R$61.12
2017-12-27    R$-31.97
2017-12-28    R$253.12
2017-12-29    R$644.43
2017-12-30    R$101.54

[1237 rows x 1 columns]

In [4]:
tabela.to_csv(
    'superstore_tratado.csv',
    index=False,
    encoding='utf-8'
)

tabela.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 1.6 MB

In [9]:
# 1. Sum the sales (using pandas .sum() is preferred over the built-in sum())
total_sales = tabela['Sales'].sum()

# 2. Format the single number using an f-string (cleaner and modern)
teste = f"R${total_sales:,.2f}"

# 3. Display your actual variable
display(teste)

'R$2,297,200.86'